---
layout: post
title: 异常
categories: Java
description: Java笔记
keywords: Java
---
# 引言  
&emsp;&emsp;java的异常处理笔记。    


# 异常
&emsp;&emsp;异常是一种`class`，因此它本身带有类型信息。异常可以在任何地方抛出，只需要在上层捕获。Java的异常是`class`，它的继承关系如下：
```ascii
                     ┌───────────┐
                     │  Object   │
                     └───────────┘
                           ▲
                           │
                     ┌───────────┐
                     │ Throwable │
                     └───────────┘
                           ▲
                 ┌─────────┴─────────┐
           ┌───────────┐       ┌───────────┐
           │   Error   │       │ Exception │
           └───────────┘       └───────────┘
                 ▲                   ▲
         ┌───────┘              ┌────┴──────────┐
┌─────────────────┐    ┌─────────────────┐┌───────────┐
│OutOfMemoryError │... │RuntimeException ││IOException│...
└─────────────────┘    └─────────────────┘└───────────┘
                                ▲
                    ┌───────────┴─────────────┐
         ┌─────────────────────┐ ┌─────────────────────────┐
         │NullPointerException │ │IllegalArgumentException │...
         └─────────────────────┘ └─────────────────────────┘
```
&emsp;&emsp;继承关系可知：`Throwable`是异常体系的根，它继承自`Object`。`Throwable`有两个体系：`Error`和`Exception`，`Error`表示**严重的错误**，程序对此一般无能为力，例如：  
- `OutOfMemoryError`：内存耗尽
- `NoClassDefFoundError`：无法加载某个Class
- `StackOverflowError`：栈溢出

&emsp;&emsp;而`Exception`则是运行时的错误，它**可以**被捕获并处理。  
&emsp;&emsp;某些异常是应用程序逻辑处理的一部分，**应该捕获并处理**。例如：  
- `NumberFormatException`：数值类型的格式错误
- `FileNotFoundException`：未找到文件
- `SocketException`：读取网络失败

&emsp;&emsp;还有一些异常是程序逻辑编写不对造成的，应该修复程序本身。例如：  
- `NullPointerException`：对某个`null`的对象调用方法或字段
- `IndexOutOfBoundsException`：数组索引越界

&emsp;&emsp;`Exception`又分为两大类：  
1. `RuntimeException`以及它的子类；
2. 非`RuntimeException`（包括`IOException`、`ReflectiveOperationException`等等）

&emsp;&emsp;Java规定：  
- **必须捕获**的异常，包括`Exception`及其子类，但不包括`RuntimeException`及其子类，这种类型的异常称为Checked Exception。
- 可以不捕获的异常，包括`Error`及其子类，`RuntimeException`及其子类。

&emsp;&emsp;注意：编译器对`RuntimeException`及其子类**不做强制捕获要求**，不是指应用程序本身不应该捕获并处理`RuntimeException`。**是否需要捕获，具体问题具体分析**。为了保证程序的健康性,在有可能出现异常的时候还是老实使用`try..catch`处理。   
&emsp;&emsp;`Exception`与`RuntimeException`的区别是面试中经常出现的问题。    
```java
String str = "123" ; // 定义字符串,全部由数字组成  
int temp = Integer.parseInt(str) ; // 将字符串变为int类型  
System.out.println(temp * temp) ; // 计算乘方
```
&emsp;&emsp;`parseInt()`的定义格式：  
```java
public static int parseInt(String s) throws NumberFormatException
```
&emsp;&emsp;此方法明明使用了**throws**关键字抛出异常,为什么不用处理,也可以编译通过？  
&emsp;&emsp;异常处理是通过5个关键字来实现的：    

| 关键词  | 说明                                  |
|---------|---------------------------------------|
| try     | 执行可能产生异常的代码                |
| catch   | 捕获异常                              |
| throw   | 抛出异常,手动抛出异常                 |
| throws  | 声明异常,声明方法可能要抛出的各种异常 |
| finally | 无论是否发生异常代码总能执行          |

&emsp;&emsp;程序运行时抛出的异常实际上就是一个异常对象。该对象中不仅封装了错误信息,还提供了些处理方法：  
- **String getMessage()**在**Exception**类中定义的方法,被继承到**所有**的异常类中,用于获得与异常相关的描述信息。  
- **void printstackTrace()**在**Exception**类中定义的方法,用于在控制台上显示有关异常的信息,不但有异常的原因,还涉及产生异常的代码行。  

## 异常捕获
&emsp;&emsp;**内部处理**  
```java
try{
//可能发生异常的代码段
} catch (异常类型 e){ 
//对异常进行处理的代码段 
}finally{
//始终执行的代码段
}
//其他代码段
```
&emsp;&emsp;在`try`发生异常则程序才会到`catch`块中执行，`catch`块代码处理完后,程序仍会向下执行而不会异常终止。发生异常语句后面的代码**不会被执行**;  
&emsp;&emsp;无论是否发生异常, `finally`块都将**执行**;`finally`块是可选的,可视具体情况决定是否添加;`finally`块必须和`try`块一起使用,不能单独存在。
&emsp;&emsp;如果没有发生异常，就正常执行`try { ... }`语句块，然后执行`finally`。如果发生了异常，就中断执行`try { ... }`语句块，然后跳转执行匹配的`catch`语句块，最后执行`finally`。  
```java
public class Main{
    public static void main(String[] args) {
        System.out.print(getNumber(0));
        System.out.print(getNumber(1));
        System.out.print(getNumber(2));
        System.out.print(getNumber(4));
    }
    public static int getNumber(int num){
        try{
            int result = 2 / num;
            return result;
        }catch (Exception exception){
            return 0;
        }finally{
            if(num == 0)return -1;
            if(num == 1)return 1;
        }
    }
}
```
&emsp;&emsp;打印：`-1110`。  
&emsp;&emsp;在 Java 中，`finally` 块中的 `return` 语句会覆盖 `try` 块中的 `return` 语句。换句话说，如果在 `try` 块中有 `return` 语句，并且在 `finally` 块中也有 `return` 语句，则最终的返回值是 `finally` 块中的返回值。这是因为 `finally` 块中的代码始终会在 `try` 块中的 `return` 语句执行之后执行，无论是否发生异常。因此，`finally` 块中的 `return` 语句会覆盖 `try` 块中的任何返回值。  
&emsp;&emsp;**多重catch**  
&emsp;&emsp;有时候,在`try`块中的代码段将有可能产生**多种**不同类型的**异常**,而我们又需要针对不同的异常类型进行不同的处理方式,那么我们就可以使用**多重**`catch`块,来分别捕获不同类型的异常。  
&emsp;&emsp;使用多个`catch`语句后，每个`catch`会分别捕获对应的`Exception`及其子类。JVM在捕获到异常后，会从上到下匹配`catch`语句，匹配到某个`catch`后，执行`catch`代码块，然后**不再**继续匹配。即多个`catch`语句**只有一个**能被执行。因此存在多个`catch`的时候，`catch`的顺序非常重要：子类必须写在前面。如果某些异常的处理逻辑相同，但是异常本身不存在继承关系，那么就得编写多条`catch`子句。
```java
try {
} catch (IOException e) {
    System.out.println("Bad input");
} catch (NumberFormatException e) {
    System.out.println("Bad input");
} catch (Exception e) {
    System.out.println("Unknown error");
}
```
&emsp;&emsp;因为处理`IOException`和`NumberFormatException`的代码是相同的，所以我们可以把它两用`|`**合并**到一起：  
```java
try {
} catch (IOException | NumberFormatException e) {
    System.out.println("Bad input");
} catch (Exception e) {
    System.out.println("Unknown error");
}
```
&emsp;&emsp;**嵌套`try/catch`**  
&emsp;&emsp;有时候,整个语句块可以产生异常,而其中的某个部分又可能产生另外的异常,而我们需要分别进行处理;这样,就可以通过嵌套`try/catch`块来完成;嵌套`try/catch`块就是在一个`try/catch`块中包含有另外的`try/catch`块。  
&emsp;&emsp;只要是方法声明的Checked Exception，不在调用层捕获，也必须在更高的调用层捕获。  
&emsp;&emsp;如果某个方法中的代码有可能引发异常,可以使用`try/catch`块进行处理,这种处理方式成为"内部处理"。  
&emsp;&emsp;如果不方便在方法内部进行处理,也可以将异常往方法外部传递,这就要使用到关键字`throws`;`throws`用于将方法内部产生的异常抛给主调方法;  
## **异常传播**
&emsp;&emsp;某个方法抛出了异常时，如果当前方法没有捕获异常，异常就会被抛到上层调用方法，直到遇到某个`try ... catch`被捕获为止：
```java
public class Main {
    public static void main(String[] args) {
        try {
            process1();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    static void process1() {
        process2();
    }
    static void process2() {
        Integer.parseInt(null); // 会抛出NumberFormatException
    }
}
```
&emsp;&emsp;因为RuntimeException可以不需要`catch`或`throws`。所以`process2()`和`process1()`可以不对异常处理，`main()`也可以不要`try/catch`。  
&emsp;&emsp;通过`printStackTrace()`可以打印出方法的调用栈，类似：  
```java
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:550)
	at java.base/java.lang.Integer.parseInt(Integer.java:685)
	at com.aotmd.Main.process2(Main.java:15)
	at com.aotmd.Main.process1(Main.java:12)
	at com.aotmd.Main.main(Main.java:6)
```
&emsp;&emsp;`printStackTrace()`对于调试错误非常有用，上述信息表示：`NumberFormatException`是在`java.lang.Integer.parseInt`方法中被抛出的，从下往上看，调用层次依次是：  
1. `main()`调用`process1()`；
2. `process1()`调用`process2()`；
3. `process2()`调用`Integer.parseInt(String)`；
4. `Integer.parseInt(String)`调用`Integer.parseInt(String, int)`。

&emsp;&emsp;查看`Integer.java`源码可知，抛出异常的方法代码如下：  
```java
public static int parseInt(String s, int radix) throws NumberFormatException {
    if (s == null) {
        throw new NumberFormatException("null");
    }
    ...
}
```
&emsp;&emsp;并且，每层调用均给出了源代码的行号，可直接定位。  
&emsp;&emsp;**方法抛出异常**:   
&emsp;&emsp; `返回值类型 方法名(参数列表) throws 异常类型{代码段}`    
&emsp;&emsp;当调用带有`throws`关键字的方法时,则**必须**放在`try/catch`块中进行监控,否则编译器将会报错;  
## **抛出异常**
&emsp;&emsp;如何抛出异常？参考`Integer.parseInt()`方法，抛出异常分两步：  
1. 创建某个`Exception`的实例；
2. 用`throw`语句抛出。

&emsp;&emsp;下面是一个例子：  
```java
void process2(String s) {
    if (s==null) {
        NullPointerException e = new NullPointerException();
        throw e;
    }
}
```
&emsp;&emsp;实际上，绝大部分抛出异常的代码都会合并写成一行：  
```java
void process2(String s) {
    if (s==null) {
        throw new NullPointerException();
    }
}
```
&emsp;&emsp;如果一个方法捕获了某个异常后，又在`catch`子句中抛出新的异常，就相当于把抛出的异常类型“转换”了：  
```java
void process1(String s) {
    try {
        process2();
    } catch (NullPointerException e) {
        throw new IllegalArgumentException();
    }
}
void process2(String s) {
    if (s==null) {
        throw new NullPointerException();
    }
}
```
&emsp;&emsp;当`process2()`抛出`NullPointerException`后，被`process1()`捕获，然后抛出`IllegalArgumentException()`。  
&emsp;&emsp;如果在`main()`中捕获`IllegalArgumentException`，我们看看打印的异常栈：  
```java
public class Main {
    public static void main(String[] args) {
        try {
            process1();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    static void process1() {
        try {
            process2();
        } catch (NullPointerException e) {
            throw new IllegalArgumentException();
        }
    }
    static void process2() {
        throw new NullPointerException();
    }
}
```
&emsp;&emsp;打印出的异常栈类似：  
```java
java.lang.IllegalArgumentException
    at Main.process1(Main.java:15)
    at Main.main(Main.java:5)
```
&emsp;&emsp;新的异常**丢失了原始异常信息**，我们已经看不到原始异常`NullPointerException`的信息了。为了能追踪到完整的异常栈，在构造异常的时候，把原始的`Exception`实例传进去，新的`Exception`就可以持有原始`Exception`信息。  
&emsp;&emsp;改进如下：`throw new IllegalArgumentException(e);`。  
&emsp;&emsp;运行代码，打印出的异常栈类似：  
```java
java.lang.IllegalArgumentException: java.lang.NullPointerException
    at Main.process1(Main.java:15)
    at Main.main(Main.java:5)
Caused by: java.lang.NullPointerException
    at Main.process2(Main.java:20)
    at Main.process1(Main.java:13)
```
&emsp;&emsp;注意到`Caused by: Xxx`，说明捕获的`IllegalArgumentException`并不是造成问题的根源，根源在于`NullPointerException`，是在`Main.process2()`方法抛出的。  
&emsp;&emsp;在代码中获取原始异常可以使用`Throwable.getCause()`方法。如果返回`null`，说明已经是“根异常”了。  
&emsp;&emsp;有了完整的异常栈的信息，我们才能快速定位并修复代码的问题。  
&emsp;&emsp; 捕获到异常并再次抛出时，一定要留住原始异常，否则很难定位第一案发现场！  
&emsp;&emsp;除了把原始的`Exception`实例传进去，也可以通过`e2.initCause(e)`方法添加e的异常信息。  
## 异常屏蔽
&emsp;&emsp;如果在执行`finally`语句时抛出异常，那么，`catch`语句的异常还能否继续抛出？例如：  
```java
public class Main {
    public static void main(String[] args) {
        try {
            Integer.parseInt("abc");
        } catch (Exception e) {
            System.out.println("catched");
            throw new RuntimeException(e);
        } finally {
            System.out.println("finally");
            throw new IllegalArgumentException();
        }
    }
}
```
&emsp;&emsp;控制台：  
```java
catched
finally
Exception in thread "main" java.lang.IllegalArgumentException
	at com.aotmd.Main.main(Main.java:12)
```
&emsp;&emsp;这说明`finally`抛出异常后，原来在`catch`中准备抛出的异常就“消失”了，因为只能抛出一个异常。没有被抛出的异常称为“被屏蔽”的异常（Suppressed Exception）。  
&emsp;&emsp;在极少数的情况下，我们需要获知所有的异常。如何保存所有的异常信息？方法是先用`origin`变量保存原始异常，然后调用`Throwable.addSuppressed()`，把原始异常添加进来，最后在`finally`抛出：  
```java
public class Main {
    public static void main(String[] args) throws Exception {
        Exception origin = null;
        try {
            System.out.println(Integer.parseInt("abc"));
        } catch (Exception e) {
            origin = e;
            throw e;
        } finally {
            Exception e = new IllegalArgumentException();
            if (origin != null) {
                e.addSuppressed(origin);
            }
            throw e;
        }
    }
}
```
&emsp;&emsp;当`catch`和`finally`都抛出了异常时，虽然`catch`的异常被屏蔽了，但是，`finally`抛出的异常仍然包含了它：  
```java
Exception in thread "main" java.lang.IllegalArgumentException
	at com.aotmd.Main.main(Main.java:12)
	Suppressed: java.lang.NumberFormatException: For input string: "abc"
		at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
		at java.base/java.lang.Integer.parseInt(Integer.java:588)
		at java.base/java.lang.Integer.parseInt(Integer.java:685)
		at com.aotmd.Main.main(Main.java:7)
```
&emsp;&emsp;通过`Throwable.getSuppressed()`可以获取所有的`Suppressed Exception`。  
&emsp;&emsp;绝大多数情况下，在`finally`中不要抛出异常。因此，我们通常不需要关心`Suppressed Exception`。  
&emsp;&emsp; **`e.printStackTrace()`和`System.out`输出顺序混乱**  
```java
package com.aotmd;
import java.util.InputMismatchException;
public class Main {
    public static void main(String[] args) {
        try {
            int i = 10/0;
            System.out.println("try - first statement");
            System.out.println("try - last statement");
        }
        catch (InputMismatchException ex) {
            System.out.println("InputMismatchException Exception");
        }catch (ArithmeticException ex) {
            //ex.printStackTrace();
            System.out.println("ArithmeticException Exception");
            ex.printStackTrace();
            //ex.printStackTrace(System.out);
        }
        System.out.println("最后执行输出语句");
    }
}
```
&emsp;&emsp;控制台：  
```java
ArithmeticException Exception
最后执行输出语句
java.lang.ArithmeticException: / by zero
	at com.aotmd.Main.main(Main.java:8)
```
&emsp;&emsp;最后写在catch块外面的那句打印输出， 在异常信息前面输出了， 本意是最后哪一个打印信息是在最后执行的。  
&emsp;&emsp;**原因**：使用 printStackTrace()的时候默认是输出到System.err中去的，而普通的输出都是放入System.out，这两者都是对上层封装的输出流，在默认情况下两者是指向Console的文本流。所以两者可能会出现同步问题。  
## **异常类型**  
&emsp;&emsp;产生异常的原因多种多样,大致有：系统资源不可用：如内存分配失败,文件打开失败,数据源连接失败等等;程序控制不当：如被零除,负数开方,数组下标越界等等。  
&emsp;&emsp;当异常发生时,程序一般会作出如下反应：发生异常的部分产生系统定义的错误信息;程序意外终止,并将控制权返回操作系统;程序中所有已分配资源的状态保持不变,这样将会导致资源泄漏。那么我们就必须对有可能产生的异常进行处理。  
&emsp;&emsp;自定义异常类一般继承于`Exception`类;`Exception`类是绝大部分异常类的父类,在异常类型不明的情况下,可以都认为是`Exception`.  
&emsp;&emsp;`Throwable`有两个直接子类,它们是：  
&emsp;&emsp;`Error`类：称为**错误类**,通常是指**系统**中的**内部错误**以及资源耗尽的错误,是比较严重的,仅靠修改程序本身是**不能**恢复执行的  
&emsp;&emsp;`Exception`类：称为**异常类**,表示程序本身**可以**处理的错误。在开发Java程序过程中进行的异常处理,主要就是针对`Exception`类及其子类的异常处理。  
&emsp;&emsp;Java 根据各个类库也定义了一些其他的异常,下面的表中列出了 Java 的非检查性异常。  

| 异常                            | 描述                                                                                                                |
|---------------------------------|---------------------------------------------------------------------------------------------------------------------|
| ArithmeticException             | 当出现异常的运算条件时,抛出此异常。例如,一个整数"除以零"时,抛出此类的一个实例。                                     |
| ArrayIndexOutOfBoundsException  | 用非法索引访问数组时抛出的异常。如果索引为负或大于等于数组大小,则该索引为非法索引。                                 |
| ArrayStoreException             | 试图将错误类型的对象存储到一个对象数组时抛出的异常。                                                                |
| ClassCastException              | 当试图将对象强制转换为不是实例的子类时,抛出该异常。                                                                 |
| IllegalArgumentException        | 抛出的异常表明向方法传递了一个不合法或不正确的参数。                                                                |
| IllegalMonitorStateException    | 抛出的异常表明某一线程已经试图等待对象的监视器,或者试图通知其他正在等待对象的监视器而本身没有指定监视器的线程。     |
| IllegalStateException           | 在非法或不适当的时间调用方法时产生的信号。换句话说,即 Java 环境或 Java 应用程序没有处于请求操作所要求的适当状态下。 |
| IllegalThreadStateException     | 线程没有处于请求操作所要求的适当状态时抛出的异常。                                                                  |
| IndexOutOfBoundsException       | 指示某排序索引(例如对数组、字符串或向量的排序)超出范围时抛出。                                                      |
| NegativeArraySizeException      | 如果应用程序试图创建大小为负的数组,则抛出该异常。                                                                   |
| NullPointerException            | 当应用程序试图在需要对象的地方使用 null 时,抛出该异常                                                               |
| NumberFormatException           | 当应用程序试图将字符串转换成一种数值类型,但该字符串不能转换为适当格式时,抛出该异常。                                |
| SecurityException               | 由安全管理器抛出的异常,指示存在安全侵犯。                                                                           |
| StringIndexOutOfBoundsException | 此异常由 String 方法抛出,指示索引或者为负,或者超出字符串的大小。                                                    |
| UnsupportedOperationException   | 当不支持请求的操作时,抛出该异常。                                                                                   |

&emsp;&emsp;下面的表中列出了 Java 定义在 **java.lang** 包中的检查性异常类。  

| 异常                       | 描述                                                                                                                           |
|----------------------------|--------------------------------------------------------------------------------------------------------------------------------|
| ClassNotFoundException     | 应用程序试图加载类时,找不到相应的类,抛出该异常。                                                                               |
| CloneNotSupportedException | 当调用 Object 类中的 clone 方法克隆对象,但该对象的类无法实现 Cloneable 接口时,抛出该异常。                                     |
| IllegalAccessException     | 拒绝访问一个类的时候,抛出该异常。                                                                                              |
| InstantiationException     | 当试图使用 Class 类中的 newInstance 方法创建一个类的实例,而指定的类对象因为是一个接口或是一个抽象类而无法实例化时,抛出该异常。 |
| InterruptedException       | 一个线程被另一个线程中断,抛出该异常。                                                                                          |
| NoSuchFieldException       | 请求的变量不存在                                                                                                               |
| NoSuchMethodException      | 请求的方法不存在                                                                                                               |

##  **自定义异常类**
&emsp;&emsp;Java标准库定义的常用异常包括：  
```ascii
Exception
├─ RuntimeException
│  ├─ NullPointerException
│  ├─ IndexOutOfBoundsException
│  ├─ SecurityException
│  │
│  └─ IllegalArgumentException
│     └─ NumberFormatException
│
├─ IOException
│  ├─ UnsupportedCharsetException
│  ├─ FileNotFoundException
│  └─ SocketException
│
├─ ParseException
├─ GeneralSecurityException
├─ SQLException
└─ TimeoutException
```
&emsp;&emsp;当我们在代码中需要抛出异常时，**尽量**使用JDK已定义的异常类型。例如，参数检查不合法，应该抛出`IllegalArgumentException`：  
```java
static void process1(int age) {
    if (age <= 0) {
        throw new IllegalArgumentException();
    }
}
```
&emsp;&emsp;在一个大型项目中，可以自定义新的异常类型，但是，保持一个合理的异常继承体系是非常重要的。  
&emsp;&emsp;一个常见的做法是自定义一个`BaseException`作为“根异常”，然后，派生出各种业务类型的异常。  
&emsp;&emsp;`BaseException`需要从一个适合的`Exception`派生，通常建议从`RuntimeException`派生：  
```java
public class BaseException extends RuntimeException {}
```
&emsp;&emsp;其他业务类型的异常就可以从`BaseException`派生：  
```java
public class UserNotFoundException extends BaseException {}
public class LoginFailedException extends BaseException {}
```
&emsp;&emsp;自定义的`BaseException`应该提供多个构造方法：  
```java
public class BaseException extends RuntimeException {
    public BaseException() {
        super();
    }
    public BaseException(String message, Throwable cause) {
        super(message, cause);
    }
    public BaseException(String message) {
        super(message);
    }
    public BaseException(Throwable cause) {
        super(cause);
    }
}
```
&emsp;&emsp;上述构造方法实际上都是原样照抄`RuntimeException`。这样，抛出异常的时候，就可以选择合适的构造方法。通过IDE可以根据父类快速生成子类的构造方法。  
&emsp;&emsp;只需要继承`Exception`类就可以自定义异常类。因为JAVA中提供的都是标准异常类(包括一些异常信息),如果需要自己想要的异常信息就可以自定义异常类。`Exception`类是绝大部分异常类的父类,在异常类型不明的情况下,可以都认为是`Exception`.  
```java
class MyException extends Exception {// 自定义异常类,继承Exception类  
    public MyException(String msg) {  
        super(msg);// 调用Exception类中有一个参数的构造方法,传递错误信息  
    }  
}  
public class NoteTest {  
    public static void main(String args[]) {  
        try {  
            throw new MyException("自定义异常。");// 抛出异常  
        } catch (Exception e) {  
            System.out.println(e);//打印错误信息:MyException: 自定义异常。  
        }  
    }  
}
```
## 空指针异常
&emsp;&emsp;好的编码习惯可以极大地降低`NullPointerException`的产生，例如：  
&emsp;&emsp;成员变量在定义时初始化：`private String name = "";`使用空字符串`""`而不是默认的`null`可避免很多`NullPointerException`，编写业务逻辑时，用空字符串`""`表示未填写比`null`安全得多。  
&emsp;&emsp;返回空字符串`""`、空数组而不是`null`：  
```java
public String[] readLinesFromFile(String file) {
    if (getFileSize(file) == 0) {
        // 返回空数组而不是null:
        return new String[0];
    }
    ...
}
```
&emsp;&emsp;这样可以使得调用方无需检查结果是否为`null`。  
&emsp;&emsp;如果调用方一定要根据`null`判断，比如返回`null`表示文件不存在，那么考虑返回`Optional<T>`。`Optional.empty()`是`Optional`类的一个静态方法，用于创建一个空的`Optional`对象。`Optional`是一个容器对象，可以包含或不包含一个非空值。使用`Optional.empty()`可以表示一个不包含任何值的情况，通常用于方法返回值，表示方法执行没有返回有效结果。  
```java
public Optional<String> readFromFile(String file) {
    if (!fileExist(file)) {
        return Optional.empty();
    }
    ...
}
```
&emsp;&emsp;这样调用方必须通过`Optional.isPresent()`判断是否有结果。  
&emsp;&emsp; **定位NullPointerException**  
&emsp;&emsp;如果产生了`NullPointerException`，例如，调用`a.b.c.x()`时产生了`NullPointerException`，原因可能是：  
- `a`是`null`；
- `a.b`是`null`；
- `a.b.c`是`null`；

&emsp;&emsp;确定到底是哪个对象是`null`以前只能打印这样的日志：  
```java
System.out.println(a);
System.out.println(a.b);
System.out.println(a.b.c);
```
&emsp;&emsp;从**Java 14**开始，如果产生了`NullPointerException`，JVM可以给出详细的信息告诉我们`null`对象到底是谁。我们来看例子：  
```java
public class Main {
    public static void main(String[] args) {
        Person p = new Person();
        System.out.println(p.address.city.toLowerCase());
    }
}
class Person {
    String[] name = new String[2];
    Address address = new Address();
}
class Address {
    String city;
    String street;
    String zipcode;
}
```
&emsp;&emsp;控制台：  
```java
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "p.address.city" is null
	at com.aotmd.Main.main(Main.java:6)
```
&emsp;&emsp;可以在`NullPointerException`的详细信息中看到类似`... because "p.address.city" is null`，意思是`city`字段为`null`，这样我们就能快速定位问题所在。  
&emsp;&emsp;这种增强的`NullPointerException`详细信息是**Java 14**新增的功能，但默认是关闭的，我们可以给JVM添加一个`-XX:+ShowCodeDetailsInExceptionMessages`参数启用它：  
```batch
java -XX:+ShowCodeDetailsInExceptionMessages Main.java
```
## 断言
&emsp;&emsp;断言（Assertion）是一种调试程序的方式。在Java中，使用`assert`关键字来实现断言。  
```java
public static void main(String[] args) {
    double x = Math.abs(-123.45);
    assert x >= 0;
    System.out.println(x);
}
```
&emsp;&emsp;语句`assert x >= 0;`即为断言，断言条件`x >= 0`预期为`true`。如果计算结果为`false`，则断言失败，抛出`AssertionError`。  
&emsp;&emsp;使用`assert`语句时，还可以添加一个可选的断言消息：  
```java
assert x >= 0 : "x must >= 0";
```
&emsp;&emsp;这样，断言失败的时候，`AssertionError`会带上消息`x must >= 0`，更加便于调试。  
&emsp;&emsp;Java断言的特点是：断言失败时会抛出`AssertionError`，导致程序结束退出。因此，断言不能用于可恢复的程序错误，只应该用于开发和测试阶段。  
&emsp;&emsp;对于可恢复的程序错误，不应该使用断言。例如：  
```java
void sort(int[] arr) {
    assert arr != null;
}
```
&emsp;&emsp;应该抛出异常并在上层捕获：  
```java
void sort(int[] arr) {
    if (arr == null) {
        throw new IllegalArgumentException("array cannot be null");
    }
}
```
&emsp;&emsp;当我们在程序中使用`assert`时，例如，一个简单的断言：  
```java
int x = -1;
assert x > 0;
System.out.println(x);
```
&emsp;&emsp;断言`x`必须大于`0`，实际上`x`为`-1`，断言肯定失败。执行上述代码，发现程序并未抛出`AssertionError`，而是正常打印了`x`的值。  
&emsp;&emsp;这是因为JVM默认关闭断言指令，即遇到`assert`语句就自动忽略了，不执行。执行`assert`语句，必须给Java虚拟机传递`-enableassertions`（可简写为`-ea`）参数启用断言。  
&emsp;&emsp;还可以有选择地对特定地类启用断言，命令行参数是：`-ea:com.itranswarp.sample.Main`，表示只对`com.itranswarp.sample.Main`这个类启用断言。或者对特定地包启用断言，命令行参数是：`-ea:com.itranswarp.sample...`（注意结尾有3个`.`），表示对`com.itranswarp.sample`这个包启动断言。  
&emsp;&emsp;实际开发中，很少使用断言。更好的方法是编写单元测试。  
## JDK Logging
&emsp;&emsp;在编写程序的过程中，发现程序运行结果与预期不符，怎么办？当然是用`System.out.println()`打印出执行过程中的某些变量，观察每一步的结果与代码逻辑是否符合，然后有针对性地修改代码。  
&emsp;&emsp;代码改好了怎么办？当然是删除没有用的`System.out.println()`语句了。  
&emsp;&emsp;如果改代码又改出问题怎么办？再加上`System.out.println()`。  
&emsp;&emsp;反复这么搞几次，很快大家就发现使用`System.out.println()`非常麻烦。  
&emsp;&emsp;怎么办？解决方法是使用日志。  
&emsp;&emsp;那什么是日志？日志就是Logging，它的目的是为了取代`System.out.println()`。  
&emsp;&emsp;输出日志，而不是用`System.out.println()`，有以下几个好处：  
1. 可以设置输出样式，避免自己每次都写`"ERROR: " + var`；
2. 可以设置输出级别，禁止某些级别输出。例如，只输出错误日志；
3. 可以被重定向到文件，这样可以在程序运行结束后查看日志；
4. 可以按包名控制日志级别，只输出某些包打的日志；
5. 可以……

&emsp;&emsp;Java标准库内置了日志包`java.util.logging`，可以直接用。  
```java
package com.aotmd;
import java.util.logging.Logger;
public class Main {
    public static void main(String[] args) {
        Logger logger = Logger.getGlobal();
        logger.info("start process...");
        logger.warning("memory is running out...");
        logger.fine("ignored.");
        logger.severe("process will be terminated...");
    }
}
```
&emsp;&emsp;运行上述代码，得到类似如下的输出：  
```batch
4:11:01 下午 com.aotmd.Main main
信息: start process...
4:11:01 下午 com.aotmd.Main main
警告: memory is running out...
4:11:01 下午 com.aotmd.Main main
严重: process will be terminated...
```
&emsp;&emsp;对比可见，使用日志最大的好处是，它自动打印了时间、调用类、调用方法等很多有用的信息。  
&emsp;&emsp;再仔细观察发现，4条日志，只打印了3条，`logger.fine()`没有打印。这是因为，日志的输出可以设定级别。JDK的Logging定义了7个日志级别，从严重到普通：  
- SEVERE
- WARNING
- INFO
- CONFIG
- FINE
- FINER
- FINEST

&emsp;&emsp;因为默认级别是INFO，因此，INFO级别以下的日志，不会被打印出来。使用日志级别的好处在于，调整级别，就可以屏蔽掉很多调试相关的日志输出。  
&emsp;&emsp;使用Java标准库内置的Logging有以下局限：  
&emsp;&emsp;Logging系统在JVM启动时读取配置文件并完成初始化，一旦开始运行`main()`方法，就无法修改配置；  
&emsp;&emsp;配置不太方便，需要在JVM启动时传递参数`-Djava.util.logging.config.file=<config-file-name>`。  
&emsp;&emsp;因此，Java标准库内置的Logging使用并不是非常广泛。  
## Commons Logging
&emsp;&emsp;和Java标准库提供的日志不同，Commons Logging是一个**第三方日志库**，它是由Apache创建的日志模块。  
&emsp;&emsp;Commons Logging的特色是，它可以挂接不同的日志系统，并通过配置文件指定挂接的日志系统。**默认**情况下，Commons Logging自动搜索并使用Log4j（Log4j是另一个流行的日志系统），如果没有找到Log4j，再使用JDK Logging。  
&emsp;&emsp;使用Commons Logging只需要和两个类打交道，通过`LogFactory`获取`Log`类的实例； 使用`Log`实例的方法打日志。  
```java
package com.aotmd;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
public class Main {
    public static void main(String[] args) {
        Log log = LogFactory.getLog(Main.class);
        log.info("start...");
        log.warn("end.");
    }
}
```
&emsp;&emsp;控制台：  
```text
4:14:37 下午 com.aotmd.Main main
信息: start...
4:14:37 下午 com.aotmd.Main main
警告: end.
```
&emsp;&emsp;Commons Logging是一个第三方提供的库，所以，必须先把它[下载](https://commons.apache.org/proper/commons-logging/download_logging.cgi)下来。下载后，解压，找到`commons-logging-1.2.jar`这个文件，再把Java源码`Main.java`放到一个目录下，例如`work`目录：  
```ascii
work
├─ commons-logging-1.2.jar
└─ Main.java
```
&emsp;&emsp;然后用`javac`编译`Main.java`，编译的时候要指定`classpath`，不然编译器找不到我们引用的`org.apache.commons.logging`包。编译命令如下：  
```batch
javac -cp commons-logging-1.2.jar Main.java
```
&emsp;&emsp;如果编译成功，那么当前目录下就会多出一个`Main.class`文件：  
```ascii
work
├─ commons-logging-1.2.jar
├─ Main.java
└─ Main.class
```
&emsp;&emsp;现在可以执行这个`Main.class`，使用`java`命令，也必须指定`classpath`，命令如下：  
```batch
java -cp .;commons-logging-1.2.jar Main
```
&emsp;&emsp;注意到传入的`classpath`有两部分：一个是`.`，一个是`commons-logging-1.2.jar`，用`;`分割。`.`表示当前目录，如果没有这个`.`，JVM不会在当前目录搜索`Main.class`，就会报错。  
&emsp;&emsp;如果在Linux或macOS下运行，注意`classpath`的分隔符不是`;`，而是`:`：  
```bash
java -cp .:commons-logging-1.2.jar Main
```
&emsp;&emsp;Commons Logging定义了6个日志级别：  
- FATAL
- ERROR
- WARNING
- INFO
- DEBUG
- TRACE

&emsp;&emsp;默认级别是`INFO`。  
&emsp;&emsp;使用Commons Logging时，如果在静态方法中引用`Log`，通常直接定义一个静态类型变量：  
```java
// 在静态方法中引用Log:
public class Main {
    static final Log log = LogFactory.getLog(Main.class);
    static void foo() {
        log.info("foo");
    }
}
```
&emsp;&emsp;在实例方法中引用`Log`，通常定义一个实例变量：  
```java
// 在实例方法中引用Log:
public class Person {
    protected final Log log = LogFactory.getLog(getClass());
    void foo() {
        log.info("foo");
    }
}
```
&emsp;&emsp;注意到实例变量log的获取方式是`LogFactory.getLog(getClass())`，虽然也可以用`LogFactory.getLog(Person.class)`，但是前一种方式有个非常大的好处，就是子类可以直接使用该`log`实例。例如：  
```java
// 在子类中使用父类实例化的log:
public class Student extends Person {
    void bar() {
        log.info("bar");
    }
}
```
&emsp;&emsp;由于Java类的动态特性，子类获取的`log`字段实际上相当于`LogFactory.getLog(Student.class)`，但却是从父类继承而来，并且无需改动代码。  
&emsp;&emsp;此外，Commons Logging的日志方法，例如`info()`，除了标准的`info(String)`外，还提供了一个非常有用的重载方法：`info(String, Throwable)`，这使得记录异常更加简单：  
```java
try {
    ...
} catch (Exception e) {
    log.error("got exception!", e);
}
```
&emsp;&emsp;为什么 `getClass()` 不是Object执行的?类比于`toString`,如果子类没重写那就是`Object`的`toString`,也就是打印`hashCode`;  
&emsp;&emsp;`getClass()`是`Object`类中的一个方法，用于返回当前对象的**运行时类**。返回的`Class`对象是由该类的静态同步方法锁定的对象。实际结果类型是`Class<? extends |X|>`，其中`|X|`是调用`getClass()`方法的表达式的静态类型的擦除。这意味着返回的`Class`对象表示调用`getClass()`的对象的**运行时类**的类型。  
&emsp;&emsp;如果严格按继承来搞，虽然理论完美了，但大家都拿不到实际类型了，实际运行就得抓狂，所以JDK的实现是`native`方法，特事特办。  
&emsp;&emsp;类似的还有：为啥interface可以直接向上转型为Object？这些统统是特例，说明了工程领域的一个深刻道理：理论再完备，落地也要考虑各种实际情况。  
## Log4j
&emsp;&emsp;前面介绍了Commons Logging，可以作为“日志接口”来使用。而真正的“日志实现”可以使用Log4j。  
&emsp;&emsp;Log4j是一种非常流行的日志框架，最新版本是2.x。  
&emsp;&emsp;Log4j是一个组件化设计的日志系统，它的架构大致如下：  
```ascii
log.info("User signed in.");
 │   ┌──────────┐    ┌──────────┐    ┌──────────┐    ┌──────────┐
 ├──>│ Appender │───>│  Filter  │───>│  Layout  │───>│ Console  │
 │   └──────────┘    └──────────┘    └──────────┘    └──────────┘
 │   ┌──────────┐    ┌──────────┐    ┌──────────┐    ┌──────────┐
 ├──>│ Appender │───>│  Filter  │───>│  Layout  │───>│   File   │
 │   └──────────┘    └──────────┘    └──────────┘    └──────────┘
 │   ┌──────────┐    ┌──────────┐    ┌──────────┐    ┌──────────┐
 └──>│ Appender │───>│  Filter  │───>│  Layout  │───>│  Socket  │
     └──────────┘    └──────────┘    └──────────┘    └──────────┘
```
&emsp;&emsp;当我们使用Log4j输出一条日志时，Log4j自动通过不同的Appender把同一条日志输出到不同的目的地。例如：  
- console：输出到屏幕；
- file：输出到文件；
- socket：通过网络输出到远程计算机；
- jdbc：输出到数据库

&emsp;&emsp;在输出日志的过程中，通过Filter来过滤哪些log需要被输出，哪些log不需要被输出。例如，仅输出`ERROR`级别的日志。  
&emsp;&emsp;最后，通过Layout来格式化日志信息，例如，自动添加日期、时间、方法名称等信息。  
&emsp;&emsp;上述结构虽然复杂，但我们在实际使用的时候，并不需要关心Log4j的API，而是通过配置文件来配置它。  
&emsp;&emsp;以XML配置为例，使用Log4j的时候，我们把一个`log4j2.xml`的文件放到`classpath`下就可以让Log4j读取配置文件并按照我们的配置来输出日志。下面是一个配置文件的例子：  
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
	<Properties>
        <!-- 定义日志格式 -->
		<Property name="log.pattern">%d{MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36}%n%msg%n%n</Property>
        <!-- 定义文件名变量 -->
		<Property name="file.err.filename">log/err.log</Property>
		<Property name="file.err.pattern">log/err.%i.log.gz</Property>
	</Properties>
    <!-- 定义Appender，即目的地 -->
	<Appenders>
        <!-- 定义输出到屏幕 -->
		<Console name="console" target="SYSTEM_OUT">
            <!-- 日志格式引用上面定义的log.pattern -->
			<PatternLayout pattern="${log.pattern}" />
		</Console>
        <!-- 定义输出到文件,文件名引用上面定义的file.err.filename -->
		<RollingFile name="err" bufferedIO="true" fileName="${file.err.filename}" filePattern="${file.err.pattern}">
			<PatternLayout pattern="${log.pattern}" />
			<Policies>
                <!-- 根据文件大小自动切割日志 -->
				<SizeBasedTriggeringPolicy size="1 MB" />
			</Policies>
            <!-- 保留最近10份 -->
			<DefaultRolloverStrategy max="10" />
		</RollingFile>
	</Appenders>
	<Loggers>
		<Root level="info">
            <!-- 对info级别的日志，输出到console -->
			<AppenderRef ref="console" level="info" />
            <!-- 对error级别的日志，输出到err，即上面定义的RollingFile -->
			<AppenderRef ref="err" level="error" />
		</Root>
	</Loggers>
</Configuration>
```
&emsp;&emsp;虽然配置Log4j比较繁琐，但一旦配置完成，使用起来就非常方便。对上面的配置文件，凡是`INFO`级别的日志，会自动输出到屏幕，而`ERROR`级别的日志，不但会输出到屏幕，还会同时输出到文件。并且，一旦日志文件达到指定大小（1MB），Log4j就会自动切割新的日志文件，并最多保留10份。  
&emsp;&emsp;有了配置文件还不够，因为Log4j也是一个第三方库，我们需要从[这里](https://logging.apache.org/log4j/2.x/download.html)下载Log4j，解压后，把以下3个jar包放到`classpath`中：  
- log4j-api-2.x.jar
- log4j-core-2.x.jar
- log4j-jcl-2.x.jar

&emsp;&emsp;因为Commons Logging会自动发现并使用Log4j，所以，把上一节下载的`commons-logging-1.2.jar`也放到`classpath`中。  
&emsp;&emsp;要打印日志，只需要按Commons Logging的写法写，不需要改动任何代码，就可以得到Log4j的日志输出，类似：  
```text
17:21:28.723 [main] INFO  com.aotmd.Main
start...
17:21:28.726 [main] WARN  com.aotmd.Main
end.
```
## SLF4J和Logback
&emsp;&emsp;前面介绍了Commons Logging和Log4j这一对好基友，它们一个负责充当日志API，一个负责实现日志底层，搭配使用非常便于开发。  
&emsp;&emsp;有的童鞋可能还听说过SLF4J和Logback。这两个东东看上去也像日志，它们又是啥？  
&emsp;&emsp;其实SLF4J类似于Commons Logging，也是一个日志接口，而Logback类似于Log4j，是一个日志的实现。  
&emsp;&emsp;为什么有了Commons Logging和Log4j，又会蹦出来SLF4J和Logback？这是因为Java有着非常悠久的开源历史，不但OpenJDK本身是开源的，而且我们用到的第三方库，几乎全部都是开源的。开源生态丰富的一个特定就是，同一个功能，可以找到若干种互相竞争的开源库。  
&emsp;&emsp;因为对Commons Logging的接口不满意，有人就搞了SLF4J。因为对Log4j的性能不满意，有人就搞了Logback。  
&emsp;&emsp;我们先来看看SLF4J对Commons Logging的接口有何改进。在Commons Logging中，我们要打印日志，有时候得这么写：  
```java
int score = 99;
p.setScore(score);
log.info("Set score " + score + " for Person " + p.getName() + " ok.");
```
&emsp;&emsp;拼字符串是一个非常麻烦的事情，所以SLF4J的日志接口改进成这样了：  
```java
int score = 99;
p.setScore(score);
logger.info("Set score {} for Person {} ok.", score, p.getName());
```
&emsp;&emsp;我们靠猜也能猜出来，SLF4J的日志接口传入的是一个带占位符的字符串，用后面的变量自动替换占位符，所以看起来更加自然。  
&emsp;&emsp;如何使用SLF4J？它的接口实际上和Commons Logging几乎一模一样：  
```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
class Main {
    final Logger logger = LoggerFactory.getLogger(getClass());
}
```
&emsp;&emsp;对比一下Commons Logging和SLF4J的接口：  

| Commons Logging                       | SLF4J                   |
| :------------------------------------ | :---------------------- |
| org.apache.commons.logging.Log        | org.slf4j.Logger        |
| org.apache.commons.logging.LogFactory | org.slf4j.LoggerFactory |

&emsp;&emsp;不同之处就是Log变成了Logger，LogFactory变成了LoggerFactory。  
&emsp;&emsp;使用SLF4J和Logback和前面讲到的使用Commons Logging加Log4j是类似的，先分别下载[SLF4J](https://www.slf4j.org/download.html)和[Logback](https://logback.qos.ch/download.html)，然后把以下jar包放到classpath下：  
- slf4j-api-1.7.x.jar
- logback-classic-1.2.x.jar
- logback-core-1.2.x.jar

&emsp;&emsp;目前支持jdk8的为：  
&emsp;&emsp;[slf4j-api-2.0.12](https://mvnrepository.com/artifact/org.slf4j/slf4j-api/2.0.12)  
&emsp;&emsp;[logback-core-1.3.14](https://mvnrepository.com/artifact/ch.qos.logback/logback-core/1.3.14)  
&emsp;&emsp;[logback-classic-1.3.14](https://mvnrepository.com/artifact/ch.qos.logback/logback-classic/1.3.14)  
&emsp;&emsp;然后使用SLF4J的Logger和LoggerFactory即可。和Log4j类似，我们仍然需要一个Logback的配置文件，把`logback.xml`放到classpath下，配置如下：  
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
		</encoder>
	</appender>
	<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
		<encoder>
			<pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
			<charset>utf-8</charset>
		</encoder>
		<file>log/output.log</file>
		<rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
			<fileNamePattern>log/output.log.%i</fileNamePattern>
		</rollingPolicy>
		<triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
			<MaxFileSize>1MB</MaxFileSize>
		</triggeringPolicy>
	</appender>
	<root level="INFO">
		<appender-ref ref="CONSOLE" />
		<appender-ref ref="FILE" />
	</root>
</configuration>
```
```java
package com.aotmd;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
public class Main {
    public static void main(String[] args) {
        Logger log = LoggerFactory.getLogger(Main.class);
        log.info("start...");
        log.warn("end.");
    }
}
```
&emsp;&emsp;运行即可获得类似如下的输出：  
```text
17:03:40.465 [main] INFO  com.aotmd.Main - start...
17:03:40.467 [main] WARN  com.aotmd.Main - end.
```
&emsp;&emsp;从目前的趋势来看，越来越多的开源项目从Commons Logging加Log4j转向了SLF4J加Logback。  
